if(IsDefined(ROOM.target))fade.goto();
if(kp_escape){
    ROOM.target=MainMenu;
}
if(room==MainMenu){
    if(DEVELOPER&&kp_enter)GoTo(START_ROOM);
}
if(kc_control&&kp_d){
    DEBUG.enabled=!DEBUG.enabled;
}
if(room==rm_death){
    if(death_room_timer.countdown()){
        ButtonStartGame();
    }
}
if(play_room){
    if(!Exists(EnemySpawner)&&!Exists(Enemy)){
        GoTo(room_next(room));
    }
}
