Trace("Initialize Macros...");
#macro Print            show_debug_message
#macro undef            undefined
#macro ftGap            10
#macro ftSize           font_get_size(ftMain)
#macro ftWidth          string_width("_")
#macro ftHeight         string_height("A")
#macro lineBreak        "\n"
#macro vk_a                                         ord("A")
#macro vk_s                                         ord("S")
#macro vk_d                                         ord("D")
#macro vk_f                                         ord("F")
#macro vk_g                                         ord("G")
#macro vk_h                                         ord("H")
#macro vk_j                                         ord("J")
#macro vk_k                                         ord("K")
#macro vk_l                                         ord("L")
#macro vk_q                                         ord("Q")
#macro vk_w                                         ord("W")
#macro vk_e                                         ord("E")
#macro vk_r                                         ord("R")
#macro vk_t                                         ord("T")
#macro vk_y                                         ord("Y")
#macro vk_u                                         ord("U")
#macro vk_i                                         ord("I")
#macro vk_o                                         ord("O")
#macro vk_p                                         ord("P")
#macro vk_z                                         ord("Z")
#macro vk_x                                         ord("X")
#macro vk_c                                         ord("C")
#macro vk_v                                         ord("V")
#macro vk_b                                         ord("B")
#macro vk_n                                         ord("N")
#macro vk_m                                         ord("M")
#macro vk_0                                         ord("0")
#macro vk_1                                         ord("1")
#macro vk_2                                         ord("2")
#macro vk_3                                         ord("3")
#macro vk_4                                         ord("4")
#macro vk_5                                         ord("5")
#macro vk_6                                         ord("6")
#macro vk_7                                         ord("7")
#macro vk_8                                         ord("8")
#macro vk_9                                         ord("9")
Trace("Initialize function macros...");
#macro null         pointer_null
#macro str          string
#macro digits       string_digits
#macro letters      string_letters
#macro lowercase    string_lower
#macro uppercase    string_upper
#macro IsString     is_string
#macro IsReal       is_real
#macro IsUndefined  is_undefined
#macro IsArray      is_array
#macro IsBool       is_bool
#macro VSExists     variable_struct_exists
#macro VSSet        variable_struct_set
#macro VSGet        variable_struct_get
#macro VIExists     variable_instance_exists
#macro VIGet        variable_instance_get
#macro VISet        variable_instance_set
#macro VGExists     variable_global_exists
#macro VGGet        variable_global_get
#macro VGSet        variable_global_set
//#macro ArrayDelete  array_delete
//#macro Exists       instance_exists
//#macro Destroy      Destroy
//#macro Nearest                  instance_nearest
#macro Number                   instance_number
#macro roomName                 room_get_name(room)
#macro objectName               object_get_name(object_index)
#macro objectParent             object_get_parent(object_index)
#macro spriteName               sprite_get_name(sprite_index)
#macro sprWidth                 sprite_width
#macro sprHeight                sprite_height
#macro AssetIndex               asset_get_index
#macro InstanceCreateLayer      instance_create_layer
#macro InstanceCreateDepth      instance_create_depth
#macro key_pressed              keyboard_check_pressed
#macro key_check                keyboard_check
#macro gamepad_pressed          gamepad_button_check_pressed
#macro gamepad_check            gamepad_button_check
#macro falloffRefDef 25
#macro falloffMaxDef 300
#macro falloffFactorDef 1
