depth=-y;
state();
if(level==1){
    if(grow_timer1.countdown()){
        levelup();
    }
}else if(level==2){
    if(grow_timer2.countdown()){
        levelup();
    }
}
if(thirst_timer.countdown()){
    thirsty=true;
}
image_speed=1+buff_aspd;
image_blend=c_white;
if(buff_aspd>0){
    image_blend=c_aqua;
}
if(buff_dmg>0){
    image_blend=c_red;
}
if(thirsty){
    image_speed=0.5+buff_aspd;
    image_blend=c_yellow;
}
